### ISSUE TITLE
About Checkpoint.

### ISSUE THREAD

**Issue by LHY-HongyangLi** [dvlab-research/3D-Box-Segment-Anything#1]
Hi @yukang2017 , this is really a nice work.
However, when running the demo, the checkpoint I downloaded in VoxelNext(https://drive.google.com/file/d/1IV7e7G9X-61KXSjMGtQo579pzDNbhwvf/view?usp=share_link) seems not to match the model. 
```
---> 45 self.voxelnext.load_state_dict(model_dict)
     46 self.point_features = {}
     47 self.device = device
RuntimeError: Error(s) in loading state_dict for VoxelNeXt:
	Unexpected key(s) in state_dict: "global_step". 
...
	size mismatch for dense_head.heads_list.5.rot.1.weight: copying a param with shape torch.Size([2, 1, 1, 128]) from checkpoint, the shape in current model is torch.Size([1, 1, 2, 128]).
	size mismatch for dense_head.heads_list.5.vel.0.0.weight: copying a param with shape torch.Size([128, 1, 1, 128]) from checkpoint, the shape in current model is torch.Size([1, 1, 128, 128]).
	size mismatch for dense_head.heads_list.5.vel.1.weight: copying a param with shape torch.Size([2, 1, 1, 128]) from checkpoint, the shape in current model is torch.Size([1, 1, 2, 128]).
	size mismatch for dense_head.heads_list.5.hm.0.0.weight: copying a param with shape torch.Size([128, 1, 1, 128]) from checkpoint, the shape in current model is torch.Size([1, 1, 128, 128]).
	size mismatch for dense_head.heads_list.5.hm.1.weight: copying a param with shape torch.Size([2, 1, 1, 128]) from checkpoint, the shape in current model is torch.Size([1, 1, 2, 128]).
...
```

**Comment by yukang2017** [comment]
Hi @LHY-HongyangLi ,

I think this is because of the difference of spconv version. What is your version? My spconv is spconv==2.1.25


Regards,
Yukon Chen

**Comment by LHY-HongyangLi** [comment]
```
> pip list | grep spconv
spconv-cu111                   2.1.25
```
Thank you for your reply, it seems not because of the difference of spconv version.

**Comment by LHY-HongyangLi** [comment]
Is the checkpoint you have tested the same as the one you have provided in VoxelNext? I download the checkpoint here
<img width="632" alt="image" src="https://user-images.githubusercontent.com/89394032/232436942-d0201f4c-3200-4325-8b0e-72c5a03bf756.png">

**Comment by LHY-HongyangLi** [comment]
It is verified that the version of spconv matters. 
After reinstalling spconv-2.3.5 to replace the original spconv-2.1.25 the problem is solved.
