### ISSUE TITLE
model参数加载问题

### ISSUE THREAD

**Issue by xinpuliu** [dvlab-research/3D-Box-Segment-Anything#2]
你好，我在load model时候，出现了参数加载不对的情况。请问这个怎么处理？
![图片](https://user-images.githubusercontent.com/61619158/232484759-0cd3000a-6e9c-4801-94eb-85d5b9c6a80a.png)

**Comment by xinpuliu** [comment]
还有就是 nuscenes_infos_10sweeps_val.pkl  这个文件在哪里呀？谢谢

**Comment by yukang2017** [comment]
Hi,

voxelnext_nuscenes_kernel1.pth
https://drive.google.com/file/d/17mQRXXUsaD0dlRzAKep3MQjfj8ugDsp9/view?usp=share_link

nuscenes_infos_10sweeps_val.pkl
https://drive.google.com/file/d/1Kaxtubzr1GofcoFz97S6qwAIG2wzhPo_/view?usp=share_link


Regards,
Yukang Chen
