### ISSUE TITLE
spconv issue 

### ISSUE THREAD

**Issue by TmacTmac1992** [dvlab-research/3D-Box-Segment-Anything#3]
Hi, Thanks for your awesome work. When I running the model, I got this issue: 
I downloaded the checkpoint of voxelnex form the link you provide and using spocnv-cu114==2.1.25 

 indice_conv(): incompatible function arguments. The following argument types are supported:
    1. (allocator: spconv.core_cc.csrc.sparse.alloc.ExternalAllocator, ext_mm: spconv.core_cc.csrc.sparse.convops.ExternalSpconvMatmul, gemm_tuner: spconv.core_cc.csrc.sparse.convops.gemmops.GemmTunerSimple, all_w_is_krsc: bool, filter_hwio: bool, features: cumm.core_cc.tensorview_bind.Tensor, filters: cumm.core_cc.tensorview_bind.Tensor, indice_pairs: cumm.core_cc.tensorview_bind.Tensor, indice_pair_num: cumm.core_cc.tensorview_bind.Tensor, arch: Tuple[int, int], num_activate_out: int, inverse: bool = False, subm: bool = False, algo: int = 0, stream_int: int = 0, bias: cumm.core_cc.tensorview_bind.Tensor = <cumm.core_cc.tensorview_bind.Tensor object at 0x7f4cf2af4270>, act_alpha: float = 0.0, act_beta: float = 0.0, act_type: cumm.core_cc.tensorview_bind.Activation = <Activation.None_: 0>, use_tf32: bool = True) -> None

Invoked with: <spconv.pytorch.cppcore.TorchAllocator object at 0x7f4cc00d65f0>, <spconv.pytorch.cppcore.TorchSpconvMatmul object at 0x7f4cc00ddc50>, <spconv.algo.GemmTunerSimple object at 0x7f4ce24cdbf0>, True, False, <cumm.core_cc.tensorview_bind.Tensor object at 0x7f4bdb27cbb0>, <cumm.core_cc.tensorview_bind.Tensor object at 0x7f4bdb27cc30>, <cumm.core_cc.tensorview_bind.Tensor object at 0x7f4bdb27c7b0>, <cumm.core_cc.tensorview_bind.Tensor object at 0x7f4bdb27c8b0>, (0, 0), 25964, False, False, 0, 0, <cumm.core_cc.tensorview_bind.Tensor object at 0x7f4cd0149ef0>, <Activation.None_: 0>, 0, <Activation.None_: 0>; kwargs: use_tf32=False

**Comment by yukang2017** [comment]
Hi,

I think this is from the version of cumm. What is your version of cumm?


Regards,
Yukang Chen

**Comment by TmacTmac1992** [comment]
Hi, 

Thanks for your quick answer  and I am using cumm-cu114 = 0.4.8 

Regards,
Kening

**Comment by TmacTmac1992** [comment]
Hi,  this is the error message: 

[Exception|indice_conv]feat=torch.Size([17253, 16]),w=torch.Size([32, 3, 3, 3, 16]),pair=torch.Size([2, 27, 17253]),pairnum=tensor([2347, 2262, 2347, 2341, 2380, 2341, 2347, 2262, 2347, 1977, 2015, 1977,
        1901, 2030, 1901, 1977, 2015, 1977, 2347, 2262, 2347, 2341, 2380, 2341,
        2347, 2262, 2347], device='cuda:0', dtype=torch.int32),act=25964,algo=ConvAlgo.Native
SPCONV_DEBUG_SAVE_PATH not found, you can specify SPCONV_DEBUG_SAVE_PATH as debug data save path to save debug data which can be attached in a issue.
Traceback (most recent call last):
  File "/home/hj002/anaconda3/envs/3d_labeling/lib/python3.7/site-packages/spconv/pytorch/conv.py", line 343, in _conv_forward
    act_type)
  File "/home/hj002/anaconda3/envs/3d_labeling/lib/python3.7/site-packages/torch/cuda/amp/autocast_mode.py", line 94, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/home/hj002/anaconda3/envs/3d_labeling/lib/python3.7/site-packages/spconv/pytorch/functional.py", line 92, in forward
    raise e
  File "/home/hj002/anaconda3/envs/3d_labeling/lib/python3.7/site-packages/spconv/pytorch/functional.py", line 85, in forward
    act_type=act_type)
  File "/home/hj002/anaconda3/envs/3d_labeling/lib/python3.7/site-packages/spconv/pytorch/ops.py", line 865, in indice_conv
python-BaseException
    use_tf32=constants.SPCONV_ALLOW_TF32)
TypeError: indice_conv(): incompatible function arguments. The following argument types are supported:
    1. (allocator: spconv.core_cc.csrc.sparse.alloc.ExternalAllocator, ext_mm: spconv.core_cc.csrc.sparse.convops.ExternalSpconvMatmul, gemm_tuner: spconv.core_cc.csrc.sparse.convops.gemmops.GemmTunerSimple, all_w_is_krsc: bool, filter_hwio: bool, features: cumm.core_cc.tensorview_bind.Tensor, filters: cumm.core_cc.tensorview_bind.Tensor, indice_pairs: cumm.core_cc.tensorview_bind.Tensor, indice_pair_num: cumm.core_cc.tensorview_bind.Tensor, arch: Tuple[int, int], num_activate_out: int, inverse: bool = False, subm: bool = False, algo: int = 0, stream_int: int = 0, bias: cumm.core_cc.tensorview_bind.Tensor = <cumm.core_cc.tensorview_bind.Tensor object at 0x7fb53332dc30>, act_alpha: float = 0.0, act_beta: float = 0.0, act_type: cumm.core_cc.tensorview_bind.Activation = <Activation.None_: 0>, use_tf32: bool = True) -> None
Invoked with: <spconv.pytorch.cppcore.TorchAllocator object at 0x7fb513fe2dd0>, <spconv.pytorch.cppcore.TorchSpconvMatmul object at 0x7fb513fe2ef0>, <spconv.algo.GemmTunerSimple object at 0x7fb522cfffb0>, True, False, <cumm.core_cc.tensorview_bind.Tensor object at 0x7fb513ffc270>, <cumm.core_cc.tensorview_bind.Tensor object at 0x7fb513ffcdf0>, <cumm.core_cc.tensorview_bind.Tensor object at 0x7fb513ffc6b0>, <cumm.core_cc.tensorview_bind.Tensor object at 0x7fb513ffc6f0>, (8, 6), 25964, False, False, 0, 0, <cumm.core_cc.tensorview_bind.Tensor object at 0x7fb513ffcc70>, <Activation.None_: 0>, 0, <Activation.None_: 0>; kwargs: use_tf32=False

**Comment by yukang2017** [comment]
Hi, I never met such issue before. It seems that the problem exists in the installation of spconv/cumm.

Can you ran the example provided in the official spconv repo?
