### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by lujiale621** [dvlab-research/3D-Box-Segment-Anything#4]
FileNotFoundError: [Errno 2] No such file or directory: '/data1/lujiale/3D-Box-Segment-Anything/samples/LIDAR_TOP/n015-2018-08-02-17-16-37+0800__LIDAR_TOP__1533201470448696.pcd.bin'

**Comment by yukang2017** [comment]
Because this demo is provided on nuScenes, do you have this dataset?

**Comment by miccall** [comment]
@yukang2017 which dataset should be download ?
<img width="960" alt="image" src="https://user-images.githubusercontent.com/20721387/233528366-326b9a3b-cc0b-473e-a55c-c2b38ed5643d.png">

**Comment by yukang2017** [comment]
Full dataset is recommended. But you can only download a small part of it, for example mini, if you just want to try several images.

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/24690867/233629525-3babbe1c-1049-4b3b-b940-5db7caecc9b1.png">

**Comment by assia855** [comment]
I download the mini full dataset (V1.0) for US and Asia and I didn't the file: `n015-2018-08-02-17-16-37+0800__LIDAR_TOP__1533201470448696.pcd.bin`
where can I find it please?

**Comment by ghost** [comment]
@assia855  I can not find it too

**Comment by AmrinKareem** [comment]
@assia855 @ngthanhtin Hi, have you been able to find it?
