### ISSUE TITLE
This project is highly dependent on the nuscenes library

### ISSUE THREAD

**Issue by miccall** [dvlab-research/3D-Box-Segment-Anything#5]
“lidar2img_rt” , “nuscenes” appear in many places, can not be generalized to many conventional image

**Comment by yukang2017** [comment]
`lidar2img_rt` is required regardless of datasets. I release a version without nuscenes in the repo of [Grounded-Segment-Anything](https://github.com/IDEA-Research/Grounded-Segment-Anything).

Please refer to this
https://github.com/IDEA-Research/Grounded-Segment-Anything/blob/main/grounded_sam_3d_box.ipynb
