### ISSUE TITLE
VoxelNext question? 

### ISSUE THREAD

**Issue by TmacTmac1992** [dvlab-research/3D-Box-Segment-Anything#7]
Hi,  can VoxelNext be replaced with other pretrained 3d detector(i.e. CenterPoint, BEVFusion)?

**Comment by yukang2017** [comment]
Hi,

I think it needs fully sparse style network. The dense head network do not have voxel-to-box pair. 
I think [FSD](https://arxiv.org/abs/2207.10035) might be a substitute.

Regards,
Yukang Chen
